"""
CANDU-6 cell -- shared composition source for the DRAGON/OpenMC control test.

WHY THIS EXISTS
DRAGON and OpenMC disagree by 4x on the RBMK void coefficient with geometry,
composition, hydrogen treatment and nuclear data all matched.  Before
concluding that is a real method difference, the OpenMC setup itself has to
be checked on a case that is NOT the RBMK.  twlup_proc/TCWU07.c2m is the
bundled CANDU-6 cell: cluster geometry, non-light-water moderator, low
enrichment, and a coolant-void branch with asserted k-inf values
(1.112290 unvoided, 1.131289 voided -> +1510 pcm).

TCWU07 runs on the IAEA WLUP library, which OpenMC cannot read, so the
control is run on DLIB_99 (ENDF/B-VIII.1) in both codes instead.  The
asserted WLUP values then no longer apply, but that is fine: what is being
tested is whether the two codes agree WITH EACH OTHER on a void coefficient
for a non-RBMK lattice.

Compositions are transcribed ONCE here, from twlup_proc/TCWU05Lib.c2m
(density + weight percent), and this file emits both the DRAGON .c2m and the
OpenMC materials.  A transcription error therefore lands in both codes
identically and cancels out of the comparison -- which is the whole point.
"""

NA = 0.60221408             # so that rho[g/cm3] * w * NA / A gives atom/b-cm

A = {  # molar masses
    "O16": 15.9949, "H2": 2.01410, "H1": 1.00794, "He4": 4.00260,
    "Nb93": 92.9064, "B": 10.811, "Zr": 91.224, "Fe56": 55.9349,
    "Ni58": 57.9353, "Cr52": 51.9405, "U235": 235.0439, "U238": 238.0508,
}
ZR_NAT = {"Zr90": 0.5145, "Zr91": 0.1122, "Zr92": 0.1715,
          "Zr94": 0.1738, "Zr96": 0.0280}
B_NAT = {"B10": 0.199, "B11": 0.801}


def _n(rho, wt, mass):
    """atom/b-cm from density (g/cm3), weight fraction, molar mass"""
    return rho * wt * NA / mass


def _zr(rho, wt):
    tot = _n(rho, wt, A["Zr"])
    return {k: tot * f for k, f in ZR_NAT.items()}


def _b(rho, wt):
    tot = _n(rho, wt, A["B"])
    return {k: tot * f for k, f in B_NAT.items()}


def compositions():
    """{mix_id: (temperature_K, {nuclide: atom/b-cm})} from TCWU05Lib.c2m"""
    m = {}

    # MIX 1 -- coolant D2O, 0.81212 g/cm3
    r = 0.81212
    m[1] = (560.66, {"O16": _n(r, 0.799449, A["O16"]),
                     "H2":  _n(r, 0.199768, A["H2"]),
                     "H1":  _n(r, 0.000783774, A["H1"])})

    # MIX 2 -- pressure tube Zr-2.5%Nb, 6.57 g/cm3
    r = 6.57
    d = {"Nb93": _n(r, 0.025, A["Nb93"])}
    d.update(_zr(r, 0.975)); d.update(_b(r, 2.10e-6))
    m[2] = (560.66, d)

    # MIX 3 -- annulus gas, He at 0.0014 g/cm3
    m[3] = (345.66, {"He4": _n(0.0014, 1.0, A["He4"])})

    # MIX 4 -- calandria tube Zr, 6.44 g/cm3
    r = 6.44
    d = {"Fe56": _n(r, 0.0016, A["Fe56"]),
         "Ni58": _n(r, 0.0006, A["Ni58"]),
         "Cr52": _n(r, 0.0011, A["Cr52"])}
    d.update(_zr(r, 0.9971)); d.update(_b(r, 3.10e-6))
    m[4] = (345.66, d)

    # MIX 5 -- moderator D2O, 1.082885 g/cm3
    r = 1.082885
    m[5] = (345.66, {"O16": _n(r, 0.798895, A["O16"]),
                     "H2":  _n(r, 0.201016, A["H2"]),
                     "H1":  _n(r, 0.0000896, A["H1"])})

    # MIX 6-9 -- natural UO2, 10.4375010 g/cm3 (four rings, same composition)
    r = 10.4375010
    fuel = {"O16":  _n(r, 0.118473, A["O16"]),
            "U235": _n(r, 0.00627118, A["U235"]),
            "U238": _n(r, 0.875256, A["U238"])}
    for i in (6, 7, 8, 9):
        m[i] = (941.29, dict(fuel))

    # MIX 10 -- cladding, same alloy as the calandria tube but hotter
    r = 6.44
    d = {"Fe56": _n(r, 0.0016, A["Fe56"]),
         "Ni58": _n(r, 0.0006, A["Ni58"]),
         "Cr52": _n(r, 0.0011, A["Cr52"])}
    d.update(_zr(r, 0.9971)); d.update(_b(r, 3.10e-6))
    m[10] = (560.66, d)
    return m


# DRAGON DLIB_99 names differ from OpenMC's for the bound scatterers.
DRAGON_NAME = {"H2": "H2_D2O", "H1": "H1_H2O"}


def dragon_c2m():
    """Emit rbmk_proc/CanduLib.c2m -- the same numbers, in DRAGON syntax."""
    L = ["*DECK CanduLib",
         "*----",
         "*  CANDU-6 compositions on DLIB_99, for the DRAGON/OpenMC control",
         "*  test.  GENERATED by openmc/candu_common.py from the density and",
         "*  weight percents in twlup_proc/TCWU05Lib.c2m -- do not hand-edit;",
         "*  the OpenMC model is built from the same source so that any",
         "*  transcription error cancels between the two codes.",
         "*----",
         "PARAMETER LIBRARY ::",
         "   EDIT 0",
         "      ::: LINKED_LIST LIBRARY ;",
         ";",
         "MODULE LIB: END: ;",
         "",
         "LIBRARY := LIB: ::",
         "  EDIT 0  NMIX 10  CTRA APOL  ANIS 2  SUBG",
         "  DEPL LIB: DRAGON FIL: DLIB_99",
         "  MIXS LIB: DRAGON FIL: DLIB_99"]
    for mid, (T, nucs) in sorted(compositions().items()):
        L.append(f"  MIX {mid:<3d} {T:8.2f}")
        ss = "  1" if mid in (6, 7, 8, 9) else ""
        for nuc, n in sorted(nucs.items()):
            dn = DRAGON_NAME.get(nuc, nuc)
            tag = ss if nuc in ("U235", "U238") else ""
            L.append(f"     {dn:<8s} = {dn:<8s} {n:.6E}{tag}")
    L += [";", "", "END: ;", "QUIT ."]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        c = compositions()
        cool, mod, fuel = c[1][1], c[5][1], c[6][1]
        print("sanity checks on the transcription:")
        print(f"  coolant  D/O      = {cool['H2']/cool['O16']:.4f}   (D2O -> 2)")
        print(f"  moderator D/O     = {mod['H2']/mod['O16']:.4f}   (D2O -> 2)")
        print(f"  fuel     O/(U)    = "
              f"{fuel['O16']/(fuel['U235']+fuel['U238']):.4f}   (UO2 -> 2)")
        print(f"  fuel     U235 at% = "
              f"{100*fuel['U235']/(fuel['U235']+fuel['U238']):.4f}  "
              f"(natural -> 0.72)")
        zr = sum(v for k, v in c[2][1].items() if k.startswith("Zr"))
        print(f"  PT       Nb wt%   = "
              f"{100*c[2][1]['Nb93']*A['Nb93']/(c[2][1]['Nb93']*A['Nb93']+zr*A['Zr']):.3f}"
              f"   (Zr-2.5Nb -> 2.5)")
    else:
        print(dragon_c2m())
