"""Generate the DRAGON method-study decks (PROGRESS.md, "Method gap").

Every deck runs the FRESH cell at dca 0.72 / 0.35 / 0.02 (TF 900 K, TG 750 K,
coolant 573 K, bound hydrogen) and prints

    METHTAB <variant-id> <dca> <k-inf>

Each variant changes exactly one thing relative to 'ctrl', which is
rbmk_h2otest.x2m's bound-hydrogen branch and must reproduce it bit for bit.
The decks are generated rather than hand-copied so that the shared text
cannot drift between them (standing rule 6).

    python gen_meth.py        # writes ../Dragon/data/rbmk_meth_*.x2m + .access links
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "Dragon", "data")

SS_TRK = "TISO 8 15.0"
FL_TRK = "TISO 15 30.0"
GEO = "GEOSS GEOFL := RbmkGeo ;"

# id: (number, hypothesis, description, lib, geo call, SS tracking, flux tracking)
VARIANTS = {
    "ctrl":  (0, "--", "production settings (= rbmk_h2otest bound H)",
              "RbmkLib", GEO, SS_TRK, FL_TRK),
    "fine1": (1, "H3", "RbmkGeoFine k=1 -- must equal ctrl",
              "RbmkLib", "GEOSS GEOFL := RbmkGeoFine :: 1 ;", SS_TRK, FL_TRK),
    "fine2": (2, "H3", "flat-flux regions split 2x, tracking densified to match",
              "RbmkLib", "GEOSS GEOFL := RbmkGeoFine :: 2 ;", SS_TRK, "TISO 20 60.0"),
    "fine4": (3, "H3", "flat-flux regions split 4x, tracking densified to match",
              "RbmkLib", "GEOSS GEOFL := RbmkGeoFine :: 4 ;", SS_TRK, "TISO 30 120.0"),
    "trk2":  (4, "H4", "flux tracking 30 angles / 60 per cm",
              "RbmkLib", GEO, SS_TRK, "TISO 30 60.0"),
    "trk4":  (5, "H4", "flux tracking 60 angles / 120 per cm",
              "RbmkLib", GEO, SS_TRK, "TISO 60 120.0"),
    "tspc":  (6, "H2", "specular (mirror) boundary on the flux solution",
              "RbmkLib", GEO, SS_TRK, "TSPC 20 30.0"),
    "zrfine4": (8, "H7+H3", "Zr self-shielded AND flat-flux regions split 4x",
              "RbmkLibZ", "GEOSS GEOFL := RbmkGeoFine :: 4 ;", SS_TRK, "TISO 30 120.0"),
    "sstrk": (9, "H6'", "self-shielding tracking 20 angles / 40 per cm (flux unchanged)",
              "RbmkLib", GEO, "TISO 20 40.0", FL_TRK),
    "shem281": (10, "H9", "SHEM-281 library (fine groups through U-238 resonances)",
              "RbmkLib", GEO, SS_TRK, FL_TRK),
    "shem295": (11, "H9", "SHEM-295 library, subgroup iteration cap raised to 300",
              "RbmkLib", GEO, SS_TRK, FL_TRK),
    "shem361": (14, "H9", "SHEM-361 library, subgroup iteration cap raised to 300",
              "RbmkLib", GEO, SS_TRK, FL_TRK),
    "zr361": (15, "H7+H9", "Zr self-shielded on SHEM-361",
              "RbmkLibZ", GEO, SS_TRK, FL_TRK),
    "best361": (16, "H7+H9+H3", "Zr self-shielded, SHEM-361, flat-flux regions split 4x",
              "RbmkLibZ", "GEOSS GEOFL := RbmkGeoFine :: 4 ;", SS_TRK, "TISO 30 120.0"),
    "zrshem": (12, "H7+H9", "Zr self-shielded on SHEM-281",
              "RbmkLibZ", GEO, SS_TRK, FL_TRK),
    "allfix": (13, "H7+H9+H3", "Zr self-shielded, SHEM-281, flat-flux regions split 4x",
              "RbmkLibZ", "GEOSS GEOFL := RbmkGeoFine :: 4 ;", SS_TRK, "TISO 30 120.0"),
    "zrss":  (7, "H7", "Zr self-shielded (RbmkLibZ; Nb93 has no subgroup data)",
              "RbmkLibZ", GEO, SS_TRK, FL_TRK),
}

TEMPLATE = """*----
*  METHOD STUDY {vid} -- hypothesis {hyp}: {desc}
*
*  GENERATED by decks/scripts/gen_meth.py -- edit that, not this file.
*  Fresh fuel, dca 0.72 / 0.35 / 0.02, TF 900 K, TG 750 K, coolant 573 K.
*  Output:  METHTAB {num} <dca> <k-inf>
*----
LINKED_LIST LIBRARY LIBSS GEOSS GEOFL TRKSS TRK SYS FLUX DONNEES ;
SEQ_BINARY  FTRKSS FTRK ;
MODULE      LIB: GEO: NXT: USS: ASM: FLU: GREP: DELETE: UTL: END: ;
PROCEDURE   {lib} {geoproc} ;

REAL tfuel := 900.0 ;
REAL tgrap := 750.0 ;
REAL tcool := 573.0 ;
INTEGER ndc := 3 ;
INTEGER iv ;
REAL dca kinf ;

DONNEES := UTL: :: CREA 'dca' <<ndc>> = 0.72 0.35 0.02 ;

{geo}
TRKSS FTRKSS := NXT: GEOSS ::
  EDIT 0 TITLE 'METH-SS' ALLG BATCH 100 {ss} ;
TRK FTRK := NXT: GEOFL ::
  EDIT 0 TITLE 'METH-FLUX' ALLG BATCH 100 {fl} ;

EVALUATE iv := 0 ;
WHILE iv ndc < DO
  EVALUATE iv := iv 1 + ;
  GREP: DONNEES :: GETVAL 'dca' <<iv>> >>dca<< ;
  LIBRARY := {lib} :: <<dca>> <<tfuel>> <<tgrap>> <<tcool>> ;
  LIBSS := USS: LIBRARY TRKSS FTRKSS :: EDIT 0 {uss} ;
  SYS   := ASM: LIBSS TRK FTRK :: EDIT 0 ;
  FLUX  := FLU: LIBSS TRK SYS :: TYPE K EXTE 1.0E-6 ;
  GREP: FLUX :: GETVAL 'K-INFINITY' 1 >>kinf<< ;
  ECHO "METHTAB" {num} dca kinf ;
  LIBRARY LIBSS SYS FLUX := DELETE: LIBRARY LIBSS SYS FLUX ;
ENDWHILE ;

ECHO "rbmk_meth_{vid} completed" ;
END: ;
QUIT .
"""

# Library binding and USS: options.  GRMIN 18 is a 172-group index (and was
# shown bit-identical to the library default there); on the SHEM structures
# the default is used instead.
ACCESS = {"shem281": "shem281.access", "shem295": "shem295.access",
          "zrshem": "shem281.access", "allfix": "shem281.access"}
ACCESS["shem361"] = ACCESS["zr361"] = ACCESS["best361"] = "shem361.access"
USS_OPT = {k: "PASS 2" for k in ACCESS}
# SHEM-295/361 hit USSIT1's default 50-iteration cap (convergence test is a
# relative 1e-4, USSIT1.f:413).  MAXS is the USS: keyword for the cap (USS.f:265).
for k in ("shem295", "shem361", "zr361", "best361"):
    USS_OPT[k] = "PASS 2 MAXST 300"

for vid, (num, hyp, desc, lib, geo, ss, fl) in VARIANTS.items():
    geoproc = "RbmkGeoFine" if "RbmkGeoFine" in geo else "RbmkGeo"
    deck = os.path.join(DATA, f"rbmk_meth_{vid}.x2m")
    with open(deck, "w") as f:
        f.write(TEMPLATE.format(vid=vid, hyp=hyp, desc=desc, lib=lib, geo=geo,
                                geoproc=geoproc, ss=ss, fl=fl, num=num,
                                uss=USS_OPT.get(vid, "PASS 2 GRMIN 18")))
    acc = os.path.join(DATA, f"rbmk_meth_{vid}.access")
    if os.path.lexists(acc):
        os.remove(acc)
    os.symlink("../../common/" + ACCESS.get(vid, "dlib99.access"), acc)
    print("wrote", os.path.relpath(deck, HERE))

# ---------------------------------------------------------------------------
# Burnup variants: rbmk_a5_void.x2m with ONE procedure swapped.  The control
# is rbmk_a5_void.x2m itself (its VOIDTAB rows).  Derived by substitution so
# the depletion and branch logic stays byte-identical to the production deck.
BU_VARIANTS = {
    "puss": ("H8", "depletion heavy nuclides self-shielded", "RbmkLib", "RbmkLibP"),
    "buzr361": ("H7+H9", "Zr self-shielded on SHEM-361 (production mesh)",
                "RbmkLib", "RbmkLibZ"),
}
# Burnup variants that also change the library binding / USS: options.
BU_ACCESS = {"buzr361": "shem361.access"}
BU_USS = {"buzr361": ("PASS 2 GRMIN 18", "PASS 2 MAXST 300")}
src = open(os.path.join(DATA, "rbmk_a5_void.x2m")).read()
for vid, (hyp, desc, old, new) in BU_VARIANTS.items():
    n = src.count(f"{old} ")
    assert n >= 3, f"expected every {old} call to be replaced, found {n}"
    body = src.replace(f"PROCEDURE   {old} ", f"PROCEDURE   {new} ")
    body = body.replace(f":= {old} ::", f":= {new} ::")
    assert f":= {old} ::" not in body
    if vid in BU_USS:
        u_old, u_new = BU_USS[vid]
        assert body.count(u_old) >= 3, f"expected every USS: call to use {u_old}"
        body = body.replace(u_old, u_new)
    head = (f"*----\n*  METHOD STUDY {vid} -- hypothesis {hyp}: {desc}\n"
            f"*  GENERATED by decks/scripts/gen_meth.py from rbmk_a5_void.x2m with\n"
            f"*  {old} -> {new}.  Edit the generator, not this file.\n*----\n")
    deck = os.path.join(DATA, f"rbmk_meth_{vid}.x2m")
    open(deck, "w").write(head + body)
    acc = os.path.join(DATA, f"rbmk_meth_{vid}.access")
    if os.path.lexists(acc):
        os.remove(acc)
    os.symlink("../../common/" + BU_ACCESS.get(vid, "dlib99.access"), acc)
    print("wrote", os.path.relpath(deck, HERE))
